DROP DATABASE `MENSA`;

CREATE SCHEMA `MENSA` DEFAULT CHARACTER SET latin1 ;

USE MENSA;

DROP TABLE MEN;
DROP TABLE USU;

CREATE TABLE USU (
    USU_ID INT NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_ID)
);

CREATE TABLE MEN (
    MEN_REM_ID INT NOT NULL,
    MEN_DES_ID INT NOT NULL,
    MENS VARCHAR(255) NOT NULL,
    HOR DATETIME NOT NULL,
    FOREIGN KEY (MEN_REM_ID) REFERENCES USU(USU_ID),
    FOREIGN KEY (MEN_DES_ID) REFERENCES USU(USU_ID)
);
